version: '2'

services:
  db:
    image: 'postgres:latest'
    container_name: db
    volumes:
      - pgdata:/var/lib/postgresql/data
    expose:
      - 5432
    ports:
      - 5432:5432
    environment:
        - POSTGRES_USER=postgres
        - POSTGRES_PASSWORD=root
        - POSTGRES_DB=mihaidb
        - PGDATA=/data/postgres
  app:
    image: 'acc-second:latest'
    container_name: app
    build:
      context: .
    expose:
      - 8080
    ports:
      - 8080:8080
    environment:
        - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/mihaidb
        - SPRING_DATASOURCE_USERNAME=postgres
        - SPRING_DATASOURCE_PASSWORD=root
        - SPRING_JPA_HIBERNATE_DDL_AUTO=update
        - POSTGRES_DB=mihaidb
    depends_on:
      - db
volumes:
  pgdata:
      
